[package]
name = "tmbot"
version = "0.0.0"
authors = ["b f <brianf@geemale.kom>"]
edition = "2018"

[dependencies]
log = "*"
regex = "*"
pretty_env_logger = "*"
actix-web = { version = "3", features = ["openssl"] }
tokio = "*"
http = "*"
openssl = { version = "0.10" }
json = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
awc = "*"
