[package]
name = "tmbot"
version = "0.0.0"
authors = ["b f <brianf@geemale.kom>"]
edition = "2018"

[dependencies]
log = "*"
env_logger = "*"
regex = "*"
actix-web = { version = "3", features = ["openssl"] }
openssl = { version = "0.10" }
serde_json = "*"
serde_urlencoded = "*"
sqlite = "*"
datetime = "*"
awc = "*"
